---
apiVersion: apps/v1
kind: Deployment
metadata:
 name: apache-d
 labels:
  app: apache2
spec:
 replicas: 1
 selector:
  matchLabels:
   app: casestudy
 template:
  metadata:
   labels:
    app: apache3
  spec:
   containers:
   - name: apache2
     image: ubuntu/apache2
     ports:
     - containerPort: 80
---


apiVersion: v1
kind: Service
metadata: 
  name: my-apache
spec:
  type: NodePort
  ports:
    - targetPort: 80
      port: 80
      nodePort: 30008
  selector:
     app: casestudy
