---
apiVersion: apps/v1
kind: Deployment
metadata:
 name: Casestudy
 labels:
  app: apache2
spec:
 replicas: 2
 selector:
  matchLabels:
   app: apache2
 template:
  metadata:
   labels:
    app: casestudy
  spec:
   containers:
   - name: cs2
     image: pav537/cs2
     ports:
     - containerPort: 3000


---


apiVersion: v1
kind: Service
metadata: 
  name: my-apache
spec:
  type: NodePort
  ports:
    - targetPort: 80
      port: 3000
      nodePort:30008
  selector:
     app: casestudy
